name: Compare and generate snapshots in Cypress tests
on:
  pull_request:
    branches: ["main"]
jobs:
  cypress-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        node-version: ["16.x"]
    name: Cypress run
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Use Node.js v${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install and build lib"
        run: npm install && npm run build
      - name: Cypress.io
        uses: cypress-io/github-action@v5.0.5
        with:
          #continue-on-error: true
          working-directory: sample-app
          start: npm start
